### ISSUE TITLE
False positive for API deprecation 1.16 for field last-applied-configuration even when apiVersion is correctly set

### ISSUE THREAD

**Issue by newtondev** [doitintl/kube-no-trouble#230]
Seems like there are false positives being returned in my cluster. The `apiVersion` is clearly set as `apps/v1`, however in the `last-applied-configuration` field there is a mention of `extensions/v1beta1`. The deployment is listed by kubent as having the deprecation.

Example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "37"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment" ........
```
