### ISSUE TITLE
batch/v1beta1 CronJob not detected

### ISSUE THREAD

**Issue by jrhunger** [doitintl/kube-no-trouble#250]
Version 0.5.1 not detecting CronJobs in my cluster like this, where apiVersion is correct but lastApplied is incorrect.
```
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata": ....
```

I think the issue is that Kind is listed in rego as CronJob**s** versus CronJob.
https://github.com/doitintl/kube-no-trouble/blob/e104055e2d271cd34a4bd0994f7e03836985edae/pkg/rules/rego/deprecated-1-25.rego#L44
