### ISSUE TITLE
Not working with client.authentication.k8s.io/v1 api

### ISSUE THREAD

**Issue by mbelang** [doitintl/kube-no-trouble#391]
I recently update to the latest authentication api and kubent stopped working

```bash
kubent       
11:20AM INF >>> Kube No Trouble `kubent` <<<
11:20AM INF version 0.6.0 (git sha 126e47b9b45550a45404b599c546bf911ffae571)
11:20AM INF Initializing collectors and retrieving data
11:20AM ERR Failed to initialize collector: <nil> error="failed to create client: exec plugin: invalid apiVersion \"client.authentication.k8s.io/v1\""
11:20AM ERR Failed to initialize collector: <nil> error="failed to create client: exec plugin: invalid apiVersion \"client.authentication.k8s.io/v1\""
11:20AM ERR Failed to initialize collector: <nil> error="failed to create client: exec plugin: invalid apiVersion \"client.authentication.k8s.io/v1\""
11:20AM INF Loaded ruleset name=custom.rego.tmpl
11:20AM INF Loaded ruleset name=deprecated-1-16.rego
11:20AM INF Loaded ruleset name=deprecated-1-22.rego
11:20AM INF Loaded ruleset name=deprecated-1-25.rego
11:20AM INF Loaded ruleset name=deprecated-1-26.rego
11:20AM INF Loaded ruleset name=deprecated-future.rego
```

kube config
```yaml
users:
- name: arn:aws:eks:ca-central-1:0123456789098:cluster/my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - --region
      - ca-central-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false

```
