### ISSUE TITLE
EKS cluster authentication issue

### ISSUE THREAD

**Issue by s2504s** [doitintl/kube-no-trouble#440]
### Error:
```
1:38PM INF >>> Kube No Trouble `kubent` <<<
1:38PM INF version 0.7.0 (git sha d1bb4e5fd6550b533b2013671aa8419d923ee042)
1:38PM INF Initializing collectors and retrieving data
1:39PM INF Retrieved 0 resources from collector name=Cluster
1:39PM ERR Failed to retrieve data from collector error="list: failed to list: Get \"https://7D44444444444444444444.sk2.us-west-1.eks.amazonaws.com/api/v1/secrets?labelSelector=owner%3Dhelm\": getting credentials: decoding stdout: no kind \"ExecCredential\" is registered for version \"client.authentication.k8s.io/v1alpha1\" in scheme \"pkg/runtime/scheme.go:100\"" name="Helm v3"
1:39PM INF Loaded ruleset name=custom.rego.tmpl
1:39PM INF Loaded ruleset name=deprecated-1-16.rego
1:39PM INF Loaded ruleset name=deprecated-1-22.rego
1:39PM INF Loaded ruleset name=deprecated-1-25.rego
1:39PM INF Loaded ruleset name=deprecated-1-26.rego
1:39PM INF Loaded ruleset name=deprecated-future.rego
```

### How to reproduce:
In order to reproduce this issue - create a kubeconfig file:
```
cat kube.conf

apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: https://7D44444444444444444444.sk2.us-west-1.eks.amazonaws.com
    certificate-authority-data: 
  name: my.cluster

contexts:
- context:
    cluster: my.cluster
    user: my.cluster
  name: my.cluster

current-context: my.cluster

users:
- name: my.cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "my-cluster"
        - "--profile"
        - "my-profile"
```
and run the app
