### ISSUE TITLE
How is the helm collector finding non-existent and old resources?

### ISSUE THREAD

**Issue by red8888** [doitintl/kube-no-trouble#469]
I'm a little confused about how this helm collector works.

When I run it it finds a lot of stuff via the helm collector that does not exist on the cluster:

```
% kubent
12:00PM INF >>> Kube No Trouble `kubent` <<<
12:00PM INF version 0.7.0 (git sha d1bb4e5fd6550b533b2013671aa8419d923ee042)
12:00PM INF Initializing collectors and retrieving data
12:00PM INF Target K8s version is 1.24.9-gke.3200
12:00PM INF Retrieved 287 resources from collector name=Cluster
12:03PM INF Retrieved 911 resources from collector name="Helm v3"
12:03PM INF Loaded ruleset name=custom.rego.tmpl
12:03PM INF Loaded ruleset name=deprecated-1-16.rego
12:03PM INF Loaded ruleset name=deprecated-1-22.rego
12:03PM INF Loaded ruleset name=deprecated-1-25.rego
12:03PM INF Loaded ruleset name=deprecated-1-26.rego
12:03PM INF Loaded ruleset name=deprecated-future.rego
```

Its finding resources that do not exist and also old API versions of existing resources. Why is this? Is it looking at all helm revisions or something? Can I have it only look at the latest helm revision of all the releases? I can confirm my apps were all deployed with the latest version of my charts which have current API versions. But its finding some resources with outdated API versions via the helm collector.

**Comment by stepanstipl** [comment]
Hi @red8888, so is `kubent` actually reporting what seems to be false positives? If so, can you share a specific example? _(the above-shared output is just info that it actually retrieved some resources, not that these use deprecated APIs)._

If it really reports issues, there might be a couple of reasons. Most typically, it's around either the resources being upgraded in-cluster, but actually being deployed with old versions and therefore having old annotations or API versions in the Helm manifests, or it's a misconception of how `kubectl`/K8S API work, and that the returned API version is selected by the client.

In any case, it would be helpful to focus on one specific example to get to the bottom of this.

**Comment by reb-xpat** [comment]
I ran in to the same issue and when I investigated the deprecated apiVersions were in the managedFields section, otherwise the apiVersion at the top level was correct.

**Comment by YaraAbdellatif** [comment]
I'm facing the same issue. However the old version is only shown in the `last-applied-configuration`
example of the resources detected by `kubent`
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"ClusterRoleBinding","metadata":{"annotations":{"rbac.authorization.kubernetes.io/autoupdate":"true"},"labels":{"eks.amazonaws.com/component":"coredns","k8s-app":"kube-dns","kubernetes.io/bootstrapping":"rbac-defaults"},"name":"system:coredns","namespace":""},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"system:coredns"},"subjects":[{"kind":"ServiceAccount","name":"coredns","namespace":"kube-system"}]}
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2019-03-10T19:45:45Z"
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
  ```
