### ISSUE TITLE
Add FAQ explaining potential false positives

### ISSUE THREAD

**Issue by stepanstipl** [doitintl/kube-no-trouble#528]
We should add FAQ section explaining false positives situations, which are likely not false (`last-applied`), as we get questions on this regularly. E.g.: [^1][^2]

[^1]: https://github.com/doitintl/kube-no-trouble/issues/316#issuecomment-1245335960
[^2]: https://github.com/doitintl/kube-no-trouble/issues/509

**Comment by sidewinder12s** [comment]
With server side apply becoming more common, wouldn't those resources be missed by kubent since it does not rely on this annotation?

**Comment by mariusmagureanu** [comment]
Hi all,

I guess I'll be joining the party of confused people. I've been successfully using kubent for multiple k8s upgrade sessions.

Now I'm preparing for ``1.26`` and getting some false positives - I hope.

See the below snippet:

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler", ...
  creationTimestamp: "2023-01-17T20:59:33Z"
...
```

According to the snippet above I'd expect for that specific HPA to not be reported against upgrading to 1.26;

Am I misunderstanding something? If so, any pointer would be highly appreciated.

Otherwise, if this indeed is a bug I'd gladly contribute with a fix.

Thank you.
