### ISSUE TITLE
[BUG] Kubent reports updated manifests as outdated if their last applied configuration is outdated

### ISSUE THREAD

**Issue by arthurgbranco** [doitintl/kube-no-trouble#619]
Example: 
```
kubent
...
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
KIND                           NAMESPACE     NAME                   API_VERSION                            REPLACE_WITH (SINCE)
MutatingWebhookConfiguration   <undefined>   pod-identity-webhook   admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)
```

```
kubectl get MutatingWebhookConfiguration pod-identity-webhook -o yaml

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1beta1"...
```

kubent should skip everything inside the annotation kubectl.kubernetes.io/last-applied-configuration while checking for api deprecations if possible.
