### ISSUE TITLE
Feature Request: Additional Kind/Version Configs

### ISSUE THREAD

**Issue by ctrought** [doitintl/kube-no-trouble#682]
It would be great to be able to provide the deprecated release & replacement API (if available) for additional kinds. Currently only the kind/version is passed via `--additional-flags (-a)` so the output information lacks the information discovered. 

Preference would be to pass all of this data in via a configuration file similar to how pluto does it.

https://pluto.docs.fairwinds.com/advanced/#adding-custom-version-checks

```
target-versions:
  custom: v1.0.0
deprecated-versions:
  - version: someother/v1beta1
    kind: AnotherCRD
    deprecated-in: v1.9.0
    removed-in: v1.16.0
    replacement-api: apps/v1
    component: custom
```

In addition providing the release the deprecated API is removed in would be useful, both for auto-discovered resources + custom.
